- hosts:  general
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'atualizando repo'
      raw:  'apt update'
    - name: 'instalando python3 e pip'
      raw:  'apt install -y python3 python3-pip'
    - name: 'intall docker python sdk'
      raw:  'pip3 install docker'
  roles:
  - { role: install_docker, tags: ["install docker"]}

- hosts:  manager
  become: yes
  roles:
  - { role: init_swarm, tags: ["initiate docker swarm and include the new managers"]}

- hosts:  worker
  become: yes
  roles:
  - { role: join_swarm, tags: ["join workers into swarm"]}