- name: 'join the managers into swarm'
  docker_swarm:
    advertise_addr: "{{ ansible_facts['enp0s8']['ipv4']['address'] }}"
    state:  join
    join_token: "{{ hostvars['TOKEN_SWARM']['manager'] }}"
    remote_addrs: "{{ hostvars['docker-1']['ansible_facts']['enp0s8']['ipv4']['address'] }}:2377"
  when: ansible_facts['fqdn'] != "docker-1"